# Generated by Django 3.2.3 on 2021-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0004_psimsuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsuser',
            name='Count of working psims',
        ),
        migrations.AddField(
            model_name='psimsuser',
            name='has_worker_completed',
            field=models.BooleanField(default=False, verbose_name='Has worker completed?'),
        ),
        migrations.AddField(
            model_name='psimsuser',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Is user seen last message?'),
        ),
    ]
