# Generated by Django 3.2.3 on 2021-06-22 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psims', '0005_auto_20210622_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psimsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psims_worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
