# Generated by Django 3.2.3 on 2021-06-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0006_alter_psimsuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.location'),
        ),
    ]
