# Generated by Django 3.2.3 on 2021-06-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0008_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AddField(
            model_name='location',
            name='out',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.psimsoutput'),
        ),
    ]
