# Generated by Django 3.2.3 on 2021-06-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0010_remove_location_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psimsoutput',
            old_name='loc',
            new_name='location',
        ),
    ]
