# Generated by Django 3.2.3 on 2021-06-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0011_rename_loc_psimsoutput_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.crop'),
        ),
    ]
