# Generated by Django 3.2.3 on 2021-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0012_psimsoutput_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='average_yield',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
