# Generated by Django 3.2.3 on 2021-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0013_psimsoutput_average_yield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsuser',
            name='has_worker_completed',
        ),
        migrations.AddField(
            model_name='psimsuser',
            name='completed_worker_id',
            field=models.IntegerField(default=0, verbose_name='Complated worker id'),
        ),
    ]
