# Generated by Django 3.2.3 on 2021-07-06 08:49

from django.db import migrations, models
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0016_auto_20210705_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornparameters',
            name='p1',
            field=psims.models.PsimsIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='cornparameters',
            name='p5',
            field=psims.models.PsimsIntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='psimsoutput',
            name='weighted_index',
            field=models.IntegerField(choices=[], null=True),
        ),
    ]
