# Generated by Django 3.2.3 on 2021-07-09 08:01

from django.db import migrations
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0019_alter_psimsoutput_weighted_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingparameters',
            name='plpoe',
            field=psims.models.PsimsIntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='plantingparameters',
            name='plpop',
            field=psims.models.PsimsIntegerField(default=45),
        ),
    ]
