# Generated by Django 3.2.3 on 2021-07-09 13:09

from django.db import migrations
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0020_auto_20210709_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingparameters',
            name='plpoe',
            field=psims.models.PsimsIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='plantingparameters',
            name='plpop',
            field=psims.models.PsimsIntegerField(default=None),
        ),
    ]
