# Generated by Django 3.2.3 on 2021-07-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0023_remove_psimsoutput_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
