# Generated by Django 3.2.3 on 2021-07-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0024_psimsoutput_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='weighted_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
