# Generated by Django 3.2.3 on 2021-07-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0025_psimsoutput_weighted_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsoutput',
            name='weighted_name',
        ),
    ]
