# Generated by Django 3.2.3 on 2021-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0026_remove_psimsoutput_weighted_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='is_weighted_index',
            field=models.BooleanField(default=False),
        ),
    ]
