# Generated by Django 3.2.3 on 2021-07-17 09:22

import django.core.validators
from django.db import migrations
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0029_alter_plantingparameters_planting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizationparameters',
            name='fertilizer_date',
            field=psims.models.PsimsIntegerField(default=198, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)]),
        ),
    ]
