# Generated by Django 3.2.3 on 2021-07-21 07:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0041_auto_20210720_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='planting_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.plantingparameters'),
        ),
        migrations.AlterField(
            model_name='plantingparameters',
            name='planting_date',
            field=psims.models.PsimsIntegerField(default=202, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)]),
        ),
    ]
