# Generated by Django 3.2.3 on 2021-07-23 07:14

import datetime
import django.core.validators
from django.db import migrations, models
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0042_auto_20210721_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingparameters',
            name='planting_date',
            field=psims.models.PsimsIntegerField(default=121, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)]),
        ),
        migrations.AlterField(
            model_name='psimsoutput',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
