# Generated by Django 3.2.3 on 2021-07-29 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0044_alter_psimsoutput_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='G1',
            new_name='g1',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='G2',
            new_name='g2',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='GDDE',
            new_name='gdde',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='KCAN',
            new_name='kcan',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='P1',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='P2',
            new_name='p2',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='P3',
            new_name='p3',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='P4',
            new_name='p4',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='P5',
            new_name='p5',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='PANTH',
            new_name='panth',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='PHINT',
            new_name='phint',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='ROPT',
            new_name='ropt',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='RTPC',
            new_name='rtpc',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='RUE',
            new_name='rue',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='STPC',
            new_name='stpc',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='TBASE',
            new_name='tbawe',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='TILFC',
            new_name='tilfc',
        ),
        migrations.RenameField(
            model_name='sorghumparameters',
            old_name='TOPT',
            new_name='topt',
        ),
        migrations.RemoveField(
            model_name='sorghumparameters',
            name='P2O',
        ),
        migrations.AddField(
            model_name='psimsoutput',
            name='fertilization_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.fertilizationparameters'),
        ),
        migrations.AddField(
            model_name='psimsoutput',
            name='irrigation_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.irrigationparameters'),
        ),
        migrations.AddField(
            model_name='psimsoutput',
            name='tillage_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.tillageparameters'),
        ),
        migrations.AddField(
            model_name='psimsoutput',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.weather'),
        ),
        migrations.AddField(
            model_name='sorghumparameters',
            name='p2o',
            field=psims.models.PsimsDecimalField(decimal_places=2, default=14, max_digits=6, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
