# Generated by Django 3.2.3 on 2021-07-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0045_auto_20210729_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsoutput',
            name='fertilization_parameters',
        ),
        migrations.RemoveField(
            model_name='psimsoutput',
            name='irrigation_parameters',
        ),
        migrations.RemoveField(
            model_name='psimsoutput',
            name='tillage_parameters',
        ),
        migrations.RemoveField(
            model_name='psimsoutput',
            name='weather',
        ),
    ]
