# Generated by Django 3.2.3 on 2021-07-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0046_auto_20210729_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='fertilizer_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.fertilizationparameters'),
        ),
        migrations.AddField(
            model_name='psimsoutput',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.weather'),
        ),
    ]
