# Generated by Django 3.2.3 on 2021-07-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0047_auto_20210730_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='irrigation_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.irrigationparameters'),
        ),
    ]
