# Generated by Django 3.2.3 on 2021-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0050_remove_psimsoutput_last_step_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='last_step_json',
            field=models.JSONField(null=True),
        ),
    ]
