# Generated by Django 3.2.3 on 2021-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0053_auto_20210802_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(default='127.0.0.1:8000'),
        ),
    ]
