# Generated by Django 3.2.3 on 2021-08-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0054_alter_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsoutput',
            name='weather',
        ),
    ]
