# Generated by Django 3.2.3 on 2021-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0055_remove_psimsoutput_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='is_era',
            field=models.BooleanField(default=False),
        ),
    ]
