# Generated by Django 3.2.3 on 2021-08-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0058_auto_20210812_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationparameters',
            name='iame',
        ),
    ]
