# Generated by Django 3.2.3 on 2021-08-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0059_remove_irrigationparameters_iame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizationparameters',
            name='fedep',
        ),
    ]
