# Generated by Django 3.2.3 on 2021-08-14 06:50

from django.db import migrations
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0060_remove_fertilizationparameters_fedep'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizationparameters',
            name='fedep',
            field=psims.models.PsimsIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='irrigationparameters',
            name='iame',
            field=psims.models.PsimsCharField(default='IR001', max_length=20),
        ),
    ]
