# Generated by Django 3.2.3 on 2021-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0063_alter_psimsoutput_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psimsoutput',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
