# Generated by Django 3.2.3 on 2021-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0064_alter_psimsoutput_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
