# Generated by Django 3.2.3 on 2021-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0065_psimsoutput_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='long_names',
            field=models.JSONField(null=True),
        ),
    ]
