# Generated by Django 3.2.3 on 2021-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0067_psimsoutput_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psimsoutput',
            name='is_weighted_index',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
