# Generated by Django 3.2.3 on 2021-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0068_alter_psimsoutput_is_weighted_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psimsoutput',
            name='is_weighted_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='psimsoutput',
            name='weighted_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
