# Generated by Django 3.2.3 on 2021-08-26 07:11

from django.db import migrations
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0069_auto_20210824_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingparameters',
            name='plplp',
            field=psims.models.PsimsIntegerField(default=25),
        ),
    ]
