# Generated by Django 3.2.3 on 2021-08-28 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psims', '0070_plantingparameters_plplp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingparameters',
            name='plplp',
            field=psims.models.PsimsIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='soybeanparameters',
            name='em-fl',
            field=psims.models.PsimsFloatField(default=23),
        ),
        migrations.AlterField(
            model_name='soybeanparameters',
            name='fl-lf',
            field=psims.models.PsimsFloatField(default=39),
        ),
        migrations.AlterField(
            model_name='soybeanparameters',
            name='fl-sd',
            field=psims.models.PsimsFloatField(default=18),
        ),
        migrations.AlterField(
            model_name='soybeanparameters',
            name='fl-sh',
            field=psims.models.PsimsFloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name='soybeanparameters',
            name='sd-pm',
            field=psims.models.PsimsFloatField(default=33),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=500)),
                ('phone_number', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=50)),
                ('crops_regions', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
