# Generated by Django 3.2.3 on 2021-08-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0071_auto_20210828_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
