# Generated by Django 3.2.3 on 2021-08-30 12:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0073_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='crops_regions',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
