# Generated by Django 3.2.3 on 2021-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0074_auto_20210830_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
