# Generated by Django 3.2.3 on 2021-09-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0075_profile_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_paid',
        ),
    ]
