# Generated by Django 3.2.3 on 2021-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0076_remove_profile_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
