# Generated by Django 3.2.3 on 2021-09-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0078_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='desctiption',
            new_name='description',
        ),
    ]
