# Generated by Django 3.2.3 on 2021-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0079_rename_desctiption_card_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
