# Generated by Django 3.2.3 on 2021-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0080_cardtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtitle',
            options={'verbose_name_plural': 'Card Title'},
        ),
        migrations.AddField(
            model_name='card',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
