# Generated by Django 3.2.3 on 2021-09-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0082_alter_card_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
