# Generated by Django 3.2.3 on 2021-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0083_alter_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='polygon_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
