# Generated by Django 3.2.3 on 2021-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0085_alter_location_polygon_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='polygon_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
