# Generated by Django 3.2.3 on 2021-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0086_alter_location_polygon_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='last_yield',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
