# Generated by Django 3.2.3 on 2021-09-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0091_alter_location_polygon_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsoutput',
            name='crop',
        ),
    ]
