# Generated by Django 3.2.3 on 2021-09-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0092_remove_psimsoutput_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='crop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
