# Generated by Django 3.2.3 on 2021-09-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0093_psimsoutput_crop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsoutput',
            name='crop_id',
        ),
        migrations.AddField(
            model_name='psimsoutput',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psims.crop'),
        ),
    ]
