# Generated by Django 3.2.3 on 2021-10-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0095_auto_20211027_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
