# Generated by Django 3.2.9 on 2021-11-03 08:35

from django.db import migrations
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0096_location_location_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psimsoutput',
            name='irrigation_parameters',
        ),
        migrations.AddField(
            model_name='plantingparameters',
            name='iame',
            field=psims.models.PsimsCharField(default='IR001', max_length=20),
        ),
        migrations.AddField(
            model_name='plantingparameters',
            name='irrig',
            field=psims.models.PsimsYesNoField(default=False),
        ),
        migrations.DeleteModel(
            name='IrrigationParameters',
        ),
    ]
