# Generated by Django 3.2.9 on 2021-11-10 08:10

from django.db import migrations, models
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0097_auto_20211103_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='HempParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csdl', psims.models.PsimsFloatField(default=13.09)),
                ('ppsen', psims.models.PsimsFloatField(default=0.294)),
                ('em-fl', psims.models.PsimsFloatField(default=19.4)),
                ('fl-sh', psims.models.PsimsFloatField(default=7)),
                ('fl-sd', psims.models.PsimsFloatField(default=15)),
                ('sd-pm', psims.models.PsimsFloatField(default=34)),
                ('fl-lf', psims.models.PsimsFloatField(default=26)),
                ('lfmax', psims.models.PsimsFloatField(default=1.03)),
                ('slavr', psims.models.PsimsFloatField(default=375)),
                ('sizlf', psims.models.PsimsFloatField(default=180)),
                ('xfrt', psims.models.PsimsFloatField(default=1)),
                ('wtpsd', psims.models.PsimsFloatField(default=0.19)),
                ('sfdur', psims.models.PsimsFloatField(default=23)),
                ('sdpdv', psims.models.PsimsFloatField(default=2.2)),
                ('podur', psims.models.PsimsFloatField(default=10)),
                ('thrsh', psims.models.PsimsFloatField(default=77)),
                ('sdpro', psims.models.PsimsFloatField(default='0.405')),
                ('sdlip', psims.models.PsimsFloatField(default=0.205)),
            ],
        ),
    ]
