# Generated by Django 3.2.9 on 2021-11-24 07:49

from django.db import migrations
import psims.models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0098_hempparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingparameters',
            name='plplp',
            field=psims.models.PsimsIntegerField(blank=True, default=None, null=True),
        ),
    ]
