# Generated by Django 3.2.9 on 2022-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0101_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='last_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
