# Generated by Django 3.2.9 on 2022-01-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psims', '0102_psimsoutput_last_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='psimsoutput',
            name='proccess_id',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
